[package]
name = "tantivy"
version = "0.16.1"
readme = "README.md"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "MIT"

[lib]
name = "tantivy"
crate-type = ["cdylib"]

[build-dependencies]
pyo3-build-config = "0.15.1"

[dependencies]
chrono = "0.4.19"
tantivy = "0.16.1"
itertools = "0.10.0"
futures = "0.3.5"

[dependencies.pyo3]
version = "0.14.5"
features = ["extension-module"]

[package.metadata.maturin]
requires-python = ">=3.7"
project-url =  { Source = "https://github.com/quickwit-inc/tantivy-py" }
